name: bofan
server:
  port: 9090
  servlet:
    contextPath: /
logging:
  level:
    org:
      springframework:
        web: INFO
  config: classpath:logback.xml
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**


#---
#spring:
#  profiles: dev
#  cbf:
#    name: "cbf-dev"
#
#---
#spring:
#  profiles: uat
#  cbf:
#    name: "cbf-uat"
#
#---
#spring:
#  profiles: prod
#  cbf:
#    name: "cbf-prod"
